from django.conf import settings


AUTH_TOKENS = settings.AUTH_TOKENS

MARKETO_HOST = AUTH_TOKENS.get('EDXAPP_MARKETO_HOST', None)
MARKETO_CLIENT_ID = AUTH_TOKENS.get('EDXAPP_MARKETO_CLIENT_ID', None)
MARKETO_CLIENT_SECRET = AUTH_TOKENS.get('EDXAPP_MARKETO_CLIENT_SECRET', None)
MARKETO_TOKEN = AUTH_TOKENS.get('EDXAPP_MARKETO_TOKEN', None)
